### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by edisonchan** [travisdowns/uarch-bench#89]
OS: ubuntu 21.04
kernel: Linux 5.14.1-051401-generic
gcc/g++: (Ubuntu 11.1.0-1ubuntu1~21.04) 11.1.0
NASM: 2.15.05
make: gmake 4.3

```
cc -MMD -Wall  -g -O2 -DGIT_VERSION=\"f88a3a8\" -DUSE_LIBPFC=1 -DUSE_BACKWARD_CPP=1 -DBACKWARD_HAS_BFD=0 -DBACKWARD_HAS_DW=0 -DUSE_PERF_TIMER=1 -Iportable-snippets -Iboost_1_70_0 -Ifmt-7.1.3/include -DUARCH_BENCH_PORTABLE=0 -c -std=c11 -o nasm-utils/nasm-utils-helper.o nasm-utils/nasm-utils-helper.c
make: cc: No such file or directory
```

**Comment by travisdowns** [comment]
Most likely the file `nasm-utils/nasm-utils-helper.c` doesn't exist for, you can confirm?

It would be because you didn't initialize submodules. See this section of the doc:

https://github.com/travisdowns/uarch-bench#building

Try running `git submodule udpate --init`.

**Comment by nemequ** [comment]
I think it's actually because `cc` isn't in the path, which is definitely weird if gcc is installed.  I'm not sure exactly what the mechanism for setting up cc/c++ on Ubuntu looks like, but the first thing I'd do would be to make sure the build-essential packages is installed.  If that doesn't work, try `update-alternatives --config cc`.

Basically (at least on Debian, I don't have a convenient Ubuntu install sitting around at the moment), there should be a symlink from `/usr/bin/cc` to `/etc/alternatives/cc`, and `/etc/alternatives/cc` should be a symlink to `/usr/bin/gcc`, but this should all be managed by update-alternatives so you shouldn't create the symlinks yourself.

If `cc` isn't properly configured you'll *probably* need to go through the same process to get `c++` configured as well.

**Comment by travisdowns** [comment]
Hi Evan, thanks for the comment!

I think you are right that this error doesn't come from `cc` itself, but some problem launching cc. Errors from within cc look more like (in this case, if `foo.c` is missing):

~~~
cc: error: foo.c: No such file or directory
~~~

Oddly though, if I try to reproduce this on a system without `cc` in the path, I still get a different error:

~~~
make: cc: Command not found
~~~

OS and make are slightly different though: Ubuntu 20.04 and make 4.2.1.

So I'm not totally sure what's going on.

@edisonchan what does `which cc` report on your system?

In any case, if the problem is something with `cc` specifically (which is usually a symlink to gcc, more or less), but `gcc` is installed fine, you can just use `gcc` directly:

~~~
CC=gcc make
~~~

Or make it permanent:

~~~
echo CC=gcc > local.mk
~~~

`local.mk` is a file where you can put any local make vars customizations.

**Comment by edisonchan** [comment]
Hi, 
yes, the problem is caused by the gcc-11 in ubuntu missing "cc".
The command below can resolved it:

`sudo ln -s /usr/bin/gcc /usr/bin/cc`
